if World.isClient then
  Event.EVENT_UPDATE_TERRITORY_OCCUPYING = Event.register("EVENT_UPDATE_TERRITORY_OCCUPYING")
  Event.UPDATE_TERRITORY_OCCUPY_STATUS = Event.register("UPDATE_TERRITORY_OCCUPY_STATUS")
  Event.INTERRUPT_TERRITORY_OCCUPY = Event.register("INTERRUPT_TERRITORY_OCCUPY")
  Event.UPDATE_TERRITORY_MAP_INFO = Event.register("UPDATE_TERRITORY_MAP_INFO")
  Event.CLOSE_AREA_TIPS = Event.register("CLOSE_AREA_TIPS")
else
end
