if World.isClient then
  Event.EVENT_RIDE_ON_CAR = Event.register("EVENT_RIDE_ON_CAR")
  Event.EVENT_RIDE_OFF_CAR = Event.register("EVENT_RIDE_OFF_CAR")
  Event.EVENT_ENTER_UNLOCK_CAR = Event.register("EVENT_ENTER_UNLOCK_CAR")
  Event.EVENT_EXIT_UNLOCK_CAR = Event.register("EVENT_EXIT_UNLOCK_CAR")
  Event.EVENT_ENTER_UNLOCK_DOOR = Event.register("EVENT_ENTER_UNLOCK_DOOR")
  Event.EVENT_EXIT_UNLOCK_DOOR = Event.register("EVENT_EXIT_UNLOCK_DOOR")
  Event.EVENT_VEHICLE_STATUS_CHANGE = Event.register("EVENT_VEHICLE_STATUS_CHANGE")
  Event.EVENT_HAS_PASSENGER = Event.register("EVENT_HAS_PASSENGER")
else
  Event.EVENT_PLAYER_ENTER_DYING = Event.register("EVENT_PLAYER_ENTER_DYING")
end
