Define.COLLISION_GROUP = {
  PART = 1,
  PLAYER = 2,
  BULLET = 4,
  BUILDING = 8,
  BOX = 16,
  TRIGGER = 32,
  VEHICLE = 64,
  VEHICLE_TRIGGER = 128,
  ATM = 256
}
Define.PLAYER_TOUCH_GROUP = Define.COLLISION_GROUP.VEHICLE_TRIGGER
Define.VEHICLE_TOUCH_GROUP_SERVER = Define.COLLISION_GROUP.VEHICLE + Define.COLLISION_GROUP.PLAYER
Define.PLAYER_TOUCH_GROUP_SERVER = Define.COLLISION_GROUP.TRIGGER
Define.EntityCollideHandlers = {
  ENTITY_COLLISION_ENTER = "ENTITY_COLLISION_ENTER",
  ENTITY_COLLISION_LEAVE = "ENTITY_COLLISION_LEAVE",
  ENTITY_COLLISION_TOUCH = "ENTITY_COLLISION_TOUCH",
  ENTITY_COLLISION_APART = "ENTITY_COLLISION_APART"
}
Define.SPEED_STATE = {
  UP = 1,
  DOWN = 2,
  NONE = 3
}
