if World.isClient then
  Event.EVENT_ITEM_DATA_HANDBAG = Event.register("EVENT_ITEM_DATA_HANDBAG")
  Event.EVENT_ITEM_DATA_WEAPONBAG = Event.register("EVENT_ITEM_DATA_WEAPONBAG")
  Event.EVENT_ITEM_DATA_CLOTHESBAG = Event.register("EVENT_ITEM_DATA_CLOTHESBAG")
  Event.EVENT_ITEM_DATA_VEHICLEBAG = Event.register("EVENT_ITEM_DATA_VEHICLEBAG")
  Event.EVENT_ITEM_DATA_COSTITEM = Event.register("EVENT_ITEM_DATA_COSTITEM")
else
end
