if World.isClient then
  Event.EVENT_BASTION_DEFENSE_PROPERTY_CHANGED = Event.register("EVENT_BASTION_DEFENSE_PROPERTY_CHANGED")
  Event.EVENT_BASTION_NOTIFY_OTHER_DIE = Event.register("EVENT_NOTIFY_OTHER_DIE")
  Event.EVENT_BASTION_NOTIFY_SELF_DIE = Event.register("EVENT_NOTIFY_SELF_DIE")
else
end
