Define.GUIDE_NPC = 101
Define.GUIDE_UNLOCK_WEAPON = 103
Define.GUIDE_GET_WEAPON = 104
Define.GUIDE_PUT_MONEY = 105
Define.GUIDE_OUT_DOOR = 106
Define.GUIDE_TIPS_UNLOCK_WEAPON = 1
Define.GUIDE_TIPS_PUT_WEAPON = 2
Define.GUIDE_TIPS_PUT_MONEY = 3
