if World.isClient then
  Event.EVENT_PASS_CARD_WIN_CLOSE = Event.register("EVENT_PASS_CARD_WIN_CLOSE")
  Event.EVENT_PASS_CARD_LEVEL_UP = Event.register("EVENT_PASS_CARD_LEVEL_UP")
  Event.EVENT_PASS_CARD_ADD_EXP = Event.register("EVENT_PASS_CARD_ADD_EXP")
  Event.EVENT_PASS_CARD_BUY_GOLD_CARD = Event.register("EVENT_PASS_CARD_BUY_GOLD_CARD")
  Event.EVENT_PASS_CARD_UNLOCK = Event.register("EVENT_PASS_CARD_UNLOCK")
  Event.EVENT_PASS_CARD_GET_REWARD = Event.register("EVENT_PASS_CARD_GET_REWARD")
  Event.EVENT_PASS_CARD_QUEST_UPDATE = Event.register("EVENT_PASS_CARD_QUEST_UPDATE")
else
  Event.EVENT_PASS_CARD_QUEST_BEHAVIOUR = Event.register("EVENT_PASS_CARD_QUEST_BEHAVIOUR")
end
