if World.isClient then
  Event.EVENT_UPDATE_GANG_APPLY_LIST = Event.register("EVENT_UPDATE_GANG_APPLY_LIST")
  Event.EVENT_REFRESH_GANG_VIEW = Event.register("EVENT_REFRESH_GANG_VIEW")
  Event.EVENT_REFRESH_GANG_OPEN_VIEW_BUTTON = Event.register("EVENT_REFRESH_GANG_OPEN_VIEW_BUTTON")
  Event.EVENT_REFRESH_PLAYER_GANG_ICON = Event.register("EVENT_REFRESH_PLAYER_GANG_ICON")
  Event.EVENT_UI_CLOSE_MINIMAP = Event.register("EVENT_UI_CLOSE_MINIMAP")
  Event.EVENT_EXIT_GANG = Event.register("EVENT_EXIT_GANG")
  Event.EVENT_UI_OPEN_DEAD = Event.register("EVENT_UI_OPEN_DEAD")
  Event.EVENT_UI_CLOSE_DEAD = Event.register("EVENT_UI_CLOSE_DEAD")
  Event.EVENT_UI_OPEN_CHAT_MINI = Event.register("EVENT_UI_OPEN_CHAT_MINI")
  Event.EVENT_OPEN_GANG_WIN = Event.register("EVENT_OPEN_GANG_WIN")
  Event.EVENT_UPDATE_ALL_APPLY_BUTTON = Event.register("EVENT_UPDATE_ALL_APPLY_BUTTON")
  Event.EVENT_PLAYER_OUT_HOME = Event.register("EVENT_PLAYER_OUT_HOME")
  Event.EVENT_TOP_GANG_UPDATE = Event.register("EVENT_TOP_GANG_UPDATE")
else
end
