if World.isClient then
  Event.EVENT_CHARACTER_STATE_ON_GROUND_UPDATE_BTN = Event.register("EVENT_CHARACTER_STATE_ON_GROUND_UPDATE_BTN")
  Event.EVENT_CHARACTER_STATE_ON_GROUND_CARRY_SUCCESS = Event.register("EVENT_CHARACTER_STATE_ON_GROUND_CARRY_SUCCESS")
  Event.EVENT_UPDATE_AUTO_HURT_SELF = Event.register("EVENT_UPDATE_AUTO_HURT_SELF")
else
end
